/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VaForm: typeof import('./../src/components/VaForm/VaForm.vue')['default']
    VaFormItem: typeof import('./../src/components/VaForm/VaFormItem.vue')['default']
    VaInlineForm: typeof import('./../src/components/VaInlineForm/VaInlineForm.vue')['default']
    VaMenu: typeof import('./../src/components/VaMenu/VaMenu.vue')['default']
    VaMenuItem: typeof import('./../src/components/VaMenu/VaMenuItem.vue')['default']
    VaSubMenu: typeof import('./../src/components/VaMenu/VaSubMenu.vue')['default']
  }
}
