/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VaForm: typeof import('./../src/components/VaForm/VaForm.vue')['default']
    VaFormItem: typeof import('./../src/components/VaForm/VaFormItem.vue')['default']
    VaInlineForm: typeof import('./../src/components/VaInlineForm/VaInlineForm.vue')['default']
    VaNavbar: typeof import('./../src/components/VaNavbar/VaNavbar.vue')['default']
  }
}
